
/*异常处理：
1、 runtime异常：程序员--抛出   vs JVM--自动处理
 2、checked异常：程序员--抛出  vs 程序员---手动处理
 
 checked异常处理：
 1、程序员手动处理异常之一：throws
 2、程序员手动异常处理之二：try catch finally 

*/

//自定义checked异常：继承
class FuException extends Exception{
	public FuException(){}
	public FuException(String message){
		super(message);
	}
}

class Demo{
	public void run(int[] arr,int index){
		
	}
}

public class DiyTest {
	public static void main(String[] args) {
		

	}

}
